### PR TITLE
[-] fix `Invalid command SET lock_timeout...` error, fixes #507

### LINKED ISSUE #507: problem getting PgBouncer metrics because of "SET lock_timeout TO '100ms';"
I have some issues collecting PgBouncer metrics.
It seems pgwatch2 is issuing these two statements to get PgBouncer version, but the first one fails:

`SET lock_timeout TO '100ms';show version`

If I login to pgbouncer at port 6432 as pgbouncer to pgbouncer DB and manually issue SET lock_timeout statement it also fails:

```
psql -h localhost -p 6432 -U pgbouncer pgbouncer
Password for user pgbouncer:
psql (14.5 (Debian 14.5-1.pgdg110+1), server 1.17.0/bouncer)
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.

pgbouncer=# SET lock_timeout TO '100ms';
ERROR:  SET failed
```

I'm using PostgreSQL 14.5, PgBouncer 1.17.0 and pgwatch2 1.9.0.

The command to start pgwatch2 is: `/usr/bin/pgwatch2-daemon -c /etc/pgwatch2/config/instances.yaml -m /etc/pgwatch2/metrics --datastore=prometheus`

The error log from pgwatch2 when I hit the prometheus endpoint:
```
2022/09/02 15:33:15 ERRO setInstanceUpDownState: [pool_pg1_postgres:instance_up] could not determine instance version, reporting as 'down': pq: invalid command 'SET lock_timeout TO '100ms';show version', use SHOW HELP;
2022/09/02 15:33:15 ERRO FetchMetrics: failed to fetch pg version for  pool_pg1_postgres pgbouncer_stats pq: invalid command 'SET lock_timeout TO '100ms';show version', use SHOW HELP;
2022/09/02 15:33:15 ERRO Collect: failed to scrape [pool_pg1_postgres:pgbouncer_stats]: pq: invalid command 'SET lock_timeout TO '100ms';show version', use SHOW HELP;
```

Content of `/etc/pgwatch2/config/instances.yaml`:

```
- unique_name: pool_pg1
  dbtype: pgbouncer
  dbname: ''
  host: localhost
  port: 6432
  user: pgbouncer
  password: secret
  sslmode: require
  stmt_timeout: 5
  is_superuser: false 
  preset_metrics: pgbouncer
  custom_metrics:
  preset_metrics_standby:
  custom_metrics_standby:
  dbname_include_pattern:
  dbname_exclude_pattern:
  is_enabled: true
  group: default
  custom_tags:
  sslrootcert: ''
  sslcert: ''
  sslkey: ''
```

I'm not entirely sure if my config is OK.
Can you please help? Thank you.

### PR DESCRIPTION
**Pull request by IlyaTsoi**
Fixed error "invalid command 'SET lock_timeout TO '100ms'" when connecting to pgbouncer DB type. https://github.com/cybertec-postgresql/pgwatch2/issues/507.
It is possible to add pgbouncer tables with the same structure as "show stats" to collect metrics from them. I was add 'show pools' table in tis commit

### CODE REVIEW

File: pgwatch2/pgwatch2.go [hunk 1]
```diff
@@ -730,7 +731,11 @@ func DBExecReadByDbUniqueName(dbUnique, metricName string, stmtTimeoutOverride i
 	}
 
 	if !useConnPooling {
-		sqlLockTimeout = "SET lock_timeout TO '100ms';"
+		if md.DBType == DBTYPE_BOUNCER || md.DBType == DBTYPE_PGPOOL {
+			sqlLockTimeout = ""
+		} else {
+			sqlLockTimeout = "SET lock_timeout TO '100ms';"
+		}
```
Comment (pashagolub) [inline pgwatch2/pgwatch2.go:738]:
```suggestion
		if IsPostgresDBType(md.DBType) {
			sqlLockTimeout = "SET lock_timeout TO '100ms';"
		} else {
			sqlLockTimeout = ""
		}
```

**Review by pashagolub — COMMENTED** [review]
Hey, thanks a lot for your help.

It is usually a good idea to provide with pull requests only atomic changes. It's better here to have two separate PRs: one for bug fixing and one with a new functionality. For example, I'm not sure if we need `pgbouncer_pool` table but I'm strongly confident we want a bug fix.

Another advice is to use self descriptive commit messages. There is no need in `Update pgwatch2.go` string. We will see that from the commit itself.

It's a good idea to create a new branch in your forked repo and then creating pull request from it and not from `master`. Doing so you may allow authors of the target repo make changes. If you want to allow anyone with push access to the upstream repository to make changes to your pull request, select _Allow edits from maintainers_.

**Comment by IlyaTsoi** [comment]
@pashagolub Thanks for the advice, I'll keep that in mind next time. I'm new to this ).

**Comment by vitabaks** [comment]
## Test

result: **not passed**

```
root@7cfb7d2bff54:~# /usr/bin/pgwatch2-daemon --version
cd2790d0f446946bb7bce5f3e063be1928c0d130 (2022-11-23T16:16:29+01:00)
```

Error:

```
2022/11/24 09:52:57 WARN main: Could not find PG version info for DB drm-pgnode01_pgbouncer_postgres, skipping shutdown check of metric worker process for pgbouncer_stats
...
2022/11/24 10:03:57 ERRO MetricGathererLoop: Total failed fetches for [drm-pgnode01_pgbouncer_postgres:pgbouncer_stats]: 12
2022/11/24 10:03:57 ERRO MetricGathererLoop: Failed to fetch metric data for [drm-pgnode01_pgbouncer_oms:pgbouncer_stats]: pq: invalid command '
', use SHOW HELP;
```

**Comment by vitabaks** [comment]
@IlyaTsoi I'm sorry, but have you tested the collection of metrics with pgbouncer? It didn't work for me (see above).

**Comment by IlyaTsoi** [comment]
@vitabaks of course! This works well for me. Maybe there is something wrong with the settings? More information required.
